FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["backend/LibraryFlow.API/LibraryFlow.API.csproj", "LibraryFlow.API/"]
COPY ["backend/LibraryFlow.Application/LibraryFlow.Application.csproj", "LibraryFlow.Application/"]
COPY ["backend/LibraryFlow.Domain/LibraryFlow.Domain.csproj", "LibraryFlow.Domain/"]
COPY ["backend/LibraryFlow.Infrastructure/LibraryFlow.Infrastructure.csproj", "LibraryFlow.Infrastructure/"]

RUN dotnet restore "LibraryFlow.API/LibraryFlow.API.csproj"

COPY backend/ .
RUN dotnet publish "LibraryFlow.API/LibraryFlow.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "LibraryFlow.API.dll"]